# Generated by Django 2.2.4 on 2019-08-07 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation_scans', '0001_initial'),
        ('members', '0001_initial'),
        ('supervisor', '0001_initial'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Member')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.Office')),
                ('reservation_scans_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation_scans.ReservationScan')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.Supervisor')),
            ],
        ),
    ]
